<?php
$agent_id = $_REQUEST['id'];
?>
<div>

    <div class="mb-3">
        <input type="hidden" class="form-control" id="agent_key" name="agent_key" value="<?php echo $agent_id; ?>">
    </div>
    
    <div>
        <div class="mb-3 position-relative">
            <input type="text" class="form-control email-compose-input" data-choices data-choices-limit="15" value="info@agent.com" data-choices-removeItem placeholder="To">
            <div class="position-absolute top-0 end-0">
                <div class="d-flex">
                    <button class="btn btn-link text-reset fw-semibold px-2" type="button" data-bs-toggle="collapse" data-bs-target="#CcRecipientsCollapse" aria-expanded="false" aria-controls="CcRecipientsCollapse">
                        Cc
                    </button>
                    <button class="btn btn-link text-reset fw-semibold px-2" type="button" data-bs-toggle="collapse" data-bs-target="#BccRecipientsCollapse" aria-expanded="false" aria-controls="BccRecipientsCollapse">
                        Bcc
                    </button>
                </div>
            </div>
        </div>
        <div class="collapse" id="CcRecipientsCollapse">
            <div class="mb-3">
                <label>Cc:</label>
                <input type="email" class="form-control" data-choices data-choices-limit="15" data-choices-removeItem placeholder="Cc recipients">
            </div>
        </div>
        <div class="collapse" id="BccRecipientsCollapse">
            <div class="mb-3">
                <label>Bcc:</label>
                <input type="email" class="form-control" data-choices data-choices-limit="15" data-choices-removeItem placeholder="Bcc recipients">
            </div>
        </div>

        <div class="mb-3">
            <input type="text" class="form-control" placeholder="Subject">
        </div>

        <div class="mb-3">
            <label class="control-label"></label>
            <textarea class="form-control post_content" id="post_content" name="post_content"></textarea>
        </div>

    </div>

</div>

<script src="apps/template/statics/assets/tinymce/js/tinymce/tinymce.min.js"></script>
<script>
    tinymce.init({
        selector: '.post_content',
        height: 600,
        menubar: true,

        plugins: [
            'advlist autolink lists link image charmap print preview anchor',
            'searchreplace visualblocks code fullscreen',
            'insertdatetime media table paste imagetools wordcount'
        ],
        toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
        content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'


    });
</script>